name: "Prune Actions by CLI"
run-name: "Prune Old Action Runs on [${{ github.repository }}] @ ${{ github.ref }} by ${{ github.actor }} with ${{ github.event_name }}"

on:
  workflow_run:
    workflows: [Codacy Security Scan]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  cleanup-old-action-runs-leaving-one:
    timeout-minutes: 3
    runs-on: self-hosted
    name: "Prune old actions leaving one"

    defaults:
      run:
        shell: zsh -l {0}

    strategy:
      fail-fast: true
      matrix:
        include:
          - restriction: "prune"

    steps:

      - name: "Checkout repository source code"
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
        timeout-minutes: 1

      - name: "Cleanup old action runs leaving the last one for each workflow"
        run: ./util/src/main/sh/clean-runs.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
