name: "Prune Caches by Branch"
run-name: "Prune Caches by Branch on [${{ github.repository }}] @ ${{ github.ref }} by ${{ github.actor }} with ${{ github.event_name }}"

on:
  workflow_dispatch:
    inputs:
      restriction:
        required: true
        type: string
        default: "no-restriction"
        description: "Optional parameter on restrictions for parallelism and early cancellation of jobs; ToDo: placeholder not yet implemented and used."
  workflow_call:
    inputs:
      restriction:
        required: true
        type: string
        default: "no-restriction"
        description: "Optional parameter on restrictions for parallelism and early cancellation of jobs; ToDo: placeholder not yet implemented and used."

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-cache-prune"
  cancel-in-progress: true

defaults:
  run:
    shell: zsh -l {0}

permissions:
  contents: write
  actions: write

jobs:

  cleanup-stale-action-caches:
    timeout-minutes: 2
    runs-on: self-hosted
    name: "Prune stale caches if used  over GH Services"

    steps:
      - name: "Cleanup stale actions caches"
        run: ./util/src/main/sh/clean-github-cache.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: "Cleanup agent-local Gradle caches"
        if: ${{ inputs.restriction == 'purge-local-caches' }}
        run: ./util/src/main/sh/check-gradle-cache.sh