name: Codacy Security Scan
# https://app.codacy.com/organizations/gh/Gervi-Hera-Vitr/dashboard

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '23 20 * * 5'

permissions:
  contents: read

jobs:
  codacy-security-scan:
    permissions:
      contents: read
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read
    name: Codacy Security Scan
    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@main # https://github.com/actions/checkout

      - uses: actions/setup-java@v4 # https://github.com/actions/setup-java
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            lab-ux-ktor/*.gradle*
            lab-ux-ktor/**/gradle-wrapper.properties

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master # https://github.com/codacy/codacy-analysis-cli-action
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 99

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: results.sarif

# https://docs.github.com/en/code-security
