name: "Codacy Security Scan"
run-name: "Codacy Security Scan on [${{ github.repository }}] @ ${{ github.ref }} by ${{ github.actor }} with ${{ github.event_name }}"
# https://app.codacy.com/organizations/gh/Gervi-Hera-Vitr/dashboard

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '23 20 * * 5'
  workflow_dispatch:

permissions:
  contents: read

jobs:

  codacy-security-scan-with-cadacy:
    runs-on: self-hosted
    name: "Codacy Security Scan with Publishing"

    permissions:
      contents: read
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read

    steps:

      - name: "Checkout repository source code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: "Run the Agent Environment introspection script"
        run: zsh ./.run/introspect.sh

      # Conditional Java setup
      - name: "Setup transient JDK 21 if instructed by the Agent Environment Scanner"
        if: env.java_correct != 'true'
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      # Conditional Gradle setup
      - name: "Setup transient Gradle 8.10 if instructed by the Agent Environment Scanner"
        if: env.gradle_correct != 'true'
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808


      - name: "Run Codacy Analysis CLI Action and generate SARIF report"
        uses: codacy/codacy-analysis-cli-action@09916000460adeeedc96b9704f86deba53e2ad5d
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 999


      - name: "Upload SARIF results to CodeQL"
        uses: github/codeql-action/upload-sarif@48c3e2675613624ea7978e5d132169f97bc3b578
        with:
          sarif_file: results.sarif

# https://docs.github.com/en/code-security
