name: "Codacy Security Scan"
run-name: "Codacy Security Scan on [${{ github.repository }}] @ ${{ github.ref }} by ${{ github.actor }} with ${{ github.event_name }}"
# https://app.codacy.com/organizations/gh/Gervi-Hera-Vitr/dashboard

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      restriction:
        required: true
        type: string

permissions:
  contents: read
  actions: read
  security-events: write

concurrency:
  group: "Codacy Group"
  cancel-in-progress: false


jobs:

  codacy-security-scan-with-codacy:
    timeout-minutes: 17
    runs-on: self-hosted
    name: "Codacy Security Scan with Publishing"

    defaults:
      run:
        shell: zsh -l {0}

    steps:

      - name: "Checkout repository source code"
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
        timeout-minutes: 3

      - name: "Run the Agent Environment introspection script"
        run: .run/introspect.sh
        timeout-minutes: 3

      # Conditional Java setup
      - name: "Setup transient JDK 21 if instructed by the Agent Environment Scanner"
        if: env.java_correct != 'true'
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b
        timeout-minutes: 5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      # Conditional Gradle setup
      - name: "Setup transient Gradle 8.10 if instructed by the Agent Environment Scanner"
        if: env.gradle_correct != 'true'
        uses: gradle/actions/setup-gradle@e55599fc4d8b81ced2a6234b0b2525b1031e93fa
        timeout-minutes: 3

      - name: "Run Codacy Analysis CLI Action and generate SARIF report"
        uses: codacy/codacy-analysis-cli-action@09916000460adeeedc96b9704f86deba53e2ad5d
        timeout-minutes: 15
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 999


      - name: "Upload SARIF results to CodeQL"
        uses: github/codeql-action/upload-sarif@f8e782af5670be7b12c0acb5b25c1c5703b931b9
        timeout-minutes: 3
        with:
          sarif_file: results.sarif

# https://docs.github.com/en/code-security
