name: "Codacy Security Scan"
run-name: "Codacy Security Scan on [${{ github.repository }}] @ ${{ github.ref }} by ${{ github.actor }} with ${{ github.event_name }}"
# https://app.codacy.com/organizations/gh/Gervi-Hera-Vitr/dashboard

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      restriction:
        required: true
        type: string

permissions:
  contents: read
  actions: read
  security-events: write

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-codacy"
  cancel-in-progress: true

defaults:
  run:
    shell: zsh -l {0}


jobs:

  code-security-scan-with-codacy:
    timeout-minutes: 17
    runs-on: self-hosted
    name: "Codacy Security Scan with Publishing"

    steps:

      - name: "Checkout repository source code"
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
        timeout-minutes: 3

      - name: "Run Codacy Analysis CLI Action and generate SARIF report"
        uses: codacy/codacy-analysis-cli-action@09916000460adeeedc96b9704f86deba53e2ad5d
        timeout-minutes: 15
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 999


      - name: "Upload SARIF results to CodeQL"
        uses: github/codeql-action/upload-sarif@f8e782af5670be7b12c0acb5b25c1c5703b931b9
        timeout-minutes: 3
        with:
          sarif_file: results.sarif

  code-security-scan-codacy-postmortem:
    timeout-minutes: 3
    runs-on: self-hosted
    needs: code-security-scan-with-codacy
    name: "Codacy Quality Scan Execution Validation and Recovery"

    steps:

      - name: "ToDo: Codacy Analysis Postmortem"
        run: |
          echo -e "\n\nCodacy Analysis Postmortem placeholder.\n\n"