name: "Greetings and Welcome!"
run-name: "Gervi Herdem Vitr Greeting for ${{ github.actor }} with ${{ github.event_name }}"

on:
  pull_request_target:
  issues:
  workflow_dispatch:

jobs:

  first-time-user-greeting:
    runs-on: self-hosted
    permissions:
      issues: write
      pull-requests: write

    steps:

      - name: "Greet first time contributors!"
        uses: actions/first-interaction@34f15e814fe48ac9312ccf29db4e74fa767cbab7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Dear Contributor, Welcome to Gervi Herdem Vitr! We're happy to have you here! Please let us know if you wish to pair on this issue. Thank you!"
          pr-message: "Dear Contributor, Congratulations on your first Pull Request @ Gervi Herdem Vitr!"
