name: "Build and Deploy Jekyll Site with GitHub Pages"
run-name: "Jekyll Build and Deploy by ${{ github.actor }} with ${{ github.event_name }}"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-jekyll-site-from-site:
    runs-on: self-hosted
    name: "Build Jekyll Site from root subproject `site`"

    env:
      BUNDLE_PATH: vendor/bundle

    steps:
      - name: "Checkout repository source code"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: |
          cd site
          bundle install

      - name: "Build Jekyll site"
        run: |
          cd site
          bundle exec jekyll build -d ../_site

      - name: "Package and Upload Project Site built Artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    runs-on: self-hosted
    needs: build-jekyll-site-from-site
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: "Deploy uploaded Artifact to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4
