name: "Build and Deploy Jekyll Site with GitHub Pages"
run-name: "Jekyll Build and Deploy by ${{ github.actor }} with ${{ github.event_name }}"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build-jekyll-site-from-site:
    runs-on: ubuntu-latest
    name: "Build Jekyll Site from root subproject `site`"

    steps:
      - name: "Checkout repository source code"
        uses: actions/checkout@v4

      - name: "Configure GitHub Pages environment Action"
        uses: actions/configure-pages@v5

      - name: "Build Project Site with Jekyll"
        uses: actions/jekyll-build-pages@main
        with:
          source: ./site
          destination: ./_site

      - name: "Package and Upload Project Site built Artifact"
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build-jekyll-site-from-site
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: "Deploy uploaded Artifact to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4

# https://github.com/actions/jekyll-build-pages
# https://github.com/actions/configure-pages
# https://github.com/actions/upload-pages-artifact
# https://github.com/actions/deploy-pages
