name: Deploy Jekyll with GitHub Pages (dependencies preinstalled)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Pages
        uses: actions/configure-pages@main

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@main
        with:
          source: ./site
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@main

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main

# https://github.com/actions/jekyll-build-pages
# https://github.com/actions/configure-pages
# https://github.com/actions/upload-pages-artifact
# https://github.com/actions/deploy-pages
