name: "Label Pull Request"
run-name: "Label Pull Request with IAW Labeling Guidelines examining content by ${{ github.actor }} with ${{ github.event_name }}"
# https://github.com/actions/labeler

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      restriction:
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: "Labeling Group"
  cancel-in-progress: false

jobs:
  label-pull-request-iaw-labeling-guidelines:
    timeout-minutes: 3
    runs-on: self-hosted
    name: "Label Pull Request with IAW Labeling Guidelines examining content"

    defaults:
      run:
        shell: zsh -l {0}

    steps:
      - name: "Label Pull Request pushing labels to GitHub Pull Request"
        uses: actions/labeler@bb8f002e4f8015d017de7c01b983424cb4c6de3f
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
