name: "Build Host Environment Checks on Push"
run-name: "Build Host Environment Checks and Introspection on each Push by ${{ github.actor }} with ${{ github.event_name }}"

on:
  workflow_dispatch:
    inputs:
      restriction:
        required: true
        type: string
        default: "no restriction"
        description: "Optional parameter on restrictions for parallelism and early cancellation of jobs; ToDo: placeholder not yet implemented and used."
  workflow_call:
    inputs:
      restriction:
        required: false
        type: string
        default: "no restriction"
        description: "Optional parameter on restrictions for parallelism and early cancellation of jobs; ToDo: placeholder not yet implemented and used."

permissions:
  contents: read
  actions: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-host-checks"
  cancel-in-progress: false

defaults:
  run:
    shell: zsh -l {0}

jobs:
  build-while-introspecting-host-runtime-environment:
    timeout-minutes: 3
    runs-on: self-hosted
    name: "Build while Introspecting Host Runtime Environment on Self-Hosted Runners"

    steps:

      - name: "Checkout repository source code at root"
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
        timeout-minutes: 1

      - name: "Run custom Introspection Script and Publish boolean values for `java_correct` and `gradle_correct` into GH Env"
        run: ./util/src/main/sh/introspect-agent.sh
        timeout-minutes: 1
