name: "Working Push"
run-name: "Push on [${{ github.repository }}] @ ${{ github.ref }} by ${{ github.actor }} with ${{ github.event_name }}"

on:
  push:
    branches-ignore:
      - main
      - 125-synchronize-all-build-agents
  workflow_dispatch:


permissions:
  contents: read
  actions: read
  security-events: write
  discussions: write
  issues: write
  pull-requests: write
  statuses: read
  packages: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-push-main"
  cancel-in-progress: false

defaults:
  run:
    shell: zsh -l {0}

jobs:

  local-build-yield-to-pull-request:
    name: "Yield to Pull Request when PR exists"
    uses: ./.github/workflows/check-push-yield.yml
    secrets: inherit
    with:
      default-branch: 'main'
      target-branch: 'main'


  local-build-host-environment-checks:
    name: "Sanity Checks build on Self-Hosted Runners"
    needs: [ local-build-yield-to-pull-request ]
    if: ${{ needs.local-build-yield-to-pull-request.outputs.bypass == 'false' }}
    uses: ./.github/workflows/push-environment-checks.yml
    with:
      restriction: "on-working-push"
    secrets: inherit

  local-build-project-dependency-hints:
    name: "Impromptu Project Dependencies Checks for Contributors"
    needs: [ local-build-yield-to-pull-request ]
    if: ${{ needs.local-build-yield-to-pull-request.outputs.bypass == 'false' }}
    uses: ./.github/workflows/push-dependency-checks.yml
    with:
      restriction: "on-working-push"
      releases-only: false
    secrets: inherit

  local-build-codeql-scan:
    name: "CodeQL Quality Scan on Self-Hosted Runners"
    needs:
      - local-build-yield-to-pull-request
      - local-build-host-environment-checks
    if: ${{ needs.local-build-yield-to-pull-request.outputs.bypass == 'false' }}
    uses: ./.github/workflows/codeql-security-scan.yml
    with:
      restriction: "working-push"
    secrets: inherit


  local-build-codacy-scan:
    name: "Codacy Security Scan on Self-Hosted Runners"
    needs:
      - local-build-yield-to-pull-request
      - local-build-host-environment-checks
    if: ${{ needs.local-build-yield-to-pull-request.outputs.bypass == 'false' }}
    uses: ./.github/workflows/codacy-security-scan.yml
    with:
      restriction: "working-push"
    secrets: inherit


  workflow-cache-prune:
    name: "Prune Caches by Branch on Self-Hosted Runners"
    needs:
      - local-build-yield-to-pull-request
      - local-build-codacy-scan
      - local-build-codeql-scan
    if: ${{ needs.local-build-yield-to-pull-request.outputs.bypass == 'false' }}
    uses: ./.github/workflows/cache-prune.yml
    secrets: inherit


  workflow-runs-prune:
    name: "Prune Stale Workflow Runs"
    needs:
      - local-build-yield-to-pull-request
      - local-build-codacy-scan
      - local-build-codeql-scan
    if: ${{ needs.local-build-yield-to-pull-request.outputs.bypass == 'false' }}
    uses: ./.github/workflows/actions-prune.yml
    secrets: inherit
    permissions:
      actions: write
      contents: write
