name: "Should working push Yield to Pull Request?"
run-name: "Is Push yielding to Pull on [${{ github.repository }}] @ ${{ github.ref }} by ${{ github.actor }} with ${{ github.event_name }}?"

on:
  workflow_call:
    inputs:
      default-branch:
        description: "Default branch of the repository"
        required: true
        type: string
        default: "main"
      target-branch:
        description: "Target branch for pull requests"
        required: false
        type: string
        default: "main"
    outputs:
      bypass:
        description: "Should the push be yielded to a Pull Request?"
        value: ${{ jobs.should-push-yield-to-pull-request.outputs.terminate }}


permissions:
  contents: read
  actions: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-push-yielding-check"
  cancel-in-progress: true

jobs:

  should-push-yield-to-pull-request:
    name: "Yield to Pull Request on Self-Hosted Runners"
    timeout-minutes: 3
    runs-on: self-hosted

    env:
      GH_TOKEN: ${{ github.token }}

    outputs:
      terminate: ${{ steps.this-branch-pr-check.outputs.skip }}

    steps:
      - name: "Check if this branch has an open pull request"
        id: this-branch-pr-check
        run: |
          echo "::notice file=push.yaml,line=46::Checking if this branch has a working pull request to yield to."
          prs=$(gh pr list \
          --repo "$GITHUB_REPOSITORY" \
          --head "$(echo ${GITHUB_REF##*/})" \
          --base "${{ inputs.target-branch }}" \
          --json title \
          --jq 'length')
          if ((prs > 0)); then
            echo "skip=true" >> "$GITHUB_OUTPUT"
            echo "::warning file=push.yaml,line=55::This branch has a working pull request to yield to => `push` run is TERMINATING due to active pull request."
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
            echo "::notice file=push.yaml,line=58::This branch has no working pull request to yield to =>`push` workflow marked to execute!"
          fi