name: "Working Push"
run-name: "Push on [${{ github.repository }}] @ ${{ github.ref }} by ${{ github.actor }} with ${{ github.event_name }}"

on:
  push:
#    branches-ignore:
#      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write
  discussions: write
  issues: write
  pull-requests: write
  statuses: read

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:

  local-build-host-environment-checks:
    name: "Sanity Checks build on Self-Hosted Runners"
    uses: ./.github/workflows/push-gates.yml
    with:
      restriction: "working-push"
    secrets: inherit
    concurrency:
      group: "${{ github.workflow }}-${{ github.ref }}"
      cancel-in-progress: true

