name: "Build Host Environment Checks on Push"
run-name: "Build Host Environment Checks and Introspection on each Push by ${{ github.actor }} with ${{ github.event_name }}"

on:
  push:
  workflow_dispatch:

jobs:
  build-while-introspecting-host-runtime-environment:
    runs-on: self-hosted
    name: "Build while Introspecting Host Runtime Environment on Self-Hosted Runners"

    permissions:
      contents: read
      discussions: write
      issues: write
      pull-requests: write
      actions: read
      statuses: read

    steps:

      - name: "Checkout repository source code at root"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: "Run custom Introspection Script and Publish boolean values for `java_correct` and `gradle_correct` into GH Env"
        run: zsh ./.run/introspect.sh

      # Conditional Java setup
      - name: "Setup transient JDK 21 if instructed by the Agent Environment Scanner"
        if: env.java_correct != 'true'
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      # Conditional Gradle setup
      - name: "Setup transient Gradle 8.10 if instructed by the Agent Environment Scanner"
        if: env.gradle_correct != 'true'
        uses: gradle/actions/setup-gradle@707359876a764dbcdb9da0b0ed08291818310c3d

      # Gradle dependency caching
      - name: "Manage caching Gradle dependencies"
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a
        with:
          path: "${HOME}/.gradle/caches"
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: "Inspect Dependency Deprecations with Gradle using `dependencyUpdates` from Ben Manes Gradle Plugin"
        working-directory: lab-ux-ktor
        run: ./gradlew dependencyUpdates
