name: "Impromptu Project Dependencies Checks"
run-name: "Early hint on Dependency Deprecations on each Push by ${{ github.actor }} with ${{ github.event_name }}"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      restriction:
        required: true
        type: string
      releases-only:
        required: true
        type: boolean
        default: false
        description: "Should this workflow be restricted to releases? (default: false)"


permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-dependency-checks"
  cancel-in-progress: true

defaults:
  run:
    shell: zsh -l {0}

jobs:
  evaluate-dependencies-as-a-hint-for-active-developement:
    timeout-minutes: 3
    runs-on: self-hosted
    name: "Build while Introspecting Host Runtime Environment on Self-Hosted Runners"

    steps:

      - name: "Inspect Dependency Deprecations with Gradle using `dependencyUpdates` from Ben Manes Gradle Plugin"
        timeout-minutes: 2
        env:
          RELEASES_ONLY: ${{ inputs.releases-only }}
        run: .run/hint-on-dependencies.sh
