name: Build action checks on Push

on: [ push ]

jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Introspection Script
        run: zsh ./.run/introspect.sh

      # Conditional Java setup
      - name: Setup Java if Needed
        if: env.java_correct != 'true'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      # Conditional Gradle setup
      - name: Setup Gradle if Needed
        if: env.gradle_correct != 'true'
        uses: gradle/actions/setup-gradle@v4

      # Gradle dependency caching
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Inspect Dependency Versions with Gradle
        working-directory: lab-ux-ktor
        run: ./gradlew dependencyUpdates
