name: Mark stale issues and pull requests
# https://github.com/actions/stale

on:
  push:
    branches: [ "main" ]
  schedule:
  - cron: '20 10 * * *'

jobs:
  stale:

    runs-on: self-hosted
    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
    - uses: actions/stale@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Closing stale issue as irrelevant. If this issue is still relevant, please open a new issue instead.'
        stale-pr-message: 'Stale pull request: Closing abandoned pull request as irrelevant. If this pull request is still relevant, please follow the [contributing guide](https://github.com/Gervi-Hera-Vitr/Gervi-Hera-Vitr/blob/main/CONTRIBUTING.md) to upgrade and reopen.'
        stale-issue-label: 'issue-has-no-activity'
        stale-pr-label: 'PR-has-no-activity'
